// admin
export const GET_STAFFS = "GET_STAFFS"
export const GET_STAFFS_SUCCESS = "GET_STAFFS_SUCCESS"
export const GET_STAFFS_FAIL = "GET_STAFFS_FAIL"

export const UPDATE_STAFFS = "UPDATE_STAFFS"
export const UPDATE_STAFFS_SUCCESS = "UPDATE_STAFFS_SUCCESS"
export const UPDATE_STAFFS_FAIL = "UPDATE_STAFFS_FAIL"